# $Id$

Name: initscripts
Version: 5.49
Release: ipl54mdk

Summary: The inittab file and the %_sysconfdir/init.d scripts
License: GPL
Group: System/Base
Packager: Dmitry V. Levin <ldv@altlinux.org>

Source: %name-%version.tar.bz2

Obsoletes: rhsound sapinit

Conflicts: kernel <= 2.2, timeconfig < 0:3.0, ppp < 0:2.3.9, wvdial < 0:1.40
Conflicts: sysklogd < 0:1.3.33, lilo < 0:21.5, e2fsprogs < 0:1.19-ipl2mdk
Conflicts: shadow-utils < 0:19990827-ipl9mdk, autofs < 4.0.0-alt0.5.pre10

PreReq: setup >= 0:2.1.9-ipl18mdk, chkconfig, gawk, grep, sed, coreutils, control
Requires: findutils >= 0:4.0.33, modutils >= 0:2.4.12-alt4, mount >= 0:2.10q-ipl1mdk
Requires: procps >= 0:2.0.7-ipl5mdk, psmisc >= 0:19-ipl2mdk
Requires: util-linux >= 0:2.10q-ipl1mdk, libreadline >= 4.3-alt2
Requires: /bin/tput

# Automatically added by buildreq on Tue Oct 15 2002
BuildRequires: glib-devel libpopt-devel

%description
The %name package contains the basic system scripts used to boot
your %distribution system, change run levels, and shut the system
down cleanly. Initscripts also contains the scripts that activate and
deactivate most network interfaces.

%prep
%setup -q

%build
%add_optflags -D_GNU_SOURCE
%make_build CFLAGS="$RPM_OPT_FLAGS"
%make_build -C mandrake CFLAGS="$RPM_OPT_FLAGS"

%install
%__mkdir_p $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc{0,1,2,3,4,5,6}.d
%__mkdir_p $RPM_BUILD_ROOT/var/{log,run/netreport}

%make_install install ROOT=$RPM_BUILD_ROOT

# Can't store symlinks in a CVS archive
ln -s ../init.d/killall $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc0.d/S00killall
ln -s ../init.d/killall $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc6.d/S00killall

ln -s ../init.d/halt $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc0.d/S01halt
ln -s ../init.d/halt $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc6.d/S01reboot

ln -s ../init.d/single $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc1.d/S00single

# S99local does not support chkconfig.
for i in `seq 2 5`; do
	ln -s ../init.d/local "$RPM_BUILD_ROOT%_sysconfdir/rc.d/rc$i.d/S99local"
done

# These are LSB compatibility symlinks. Some day
# the actual files will be here instead of symlinks
for i in `seq 0 6`; do
	ln -s rc.d/rc$i.d $RPM_BUILD_ROOT%_sysconfdir/rc$i.d
done
for i in init.d; do
	ln -s rc.d/$i $RPM_BUILD_ROOT%_sysconfdir/$i
done

%make_install install -C mandrake ROOT=$RPM_BUILD_ROOT

touch $RPM_BUILD_ROOT/var/{log/wtmp,run/utmp}
touch $RPM_BUILD_ROOT%_sysconfdir/sysconfig/{clock,i18n,keyboard,mouse,network,system}
chmod -R +x $RPM_BUILD_ROOT%_sysconfdir/{rc.d,sysconfig}
touch $RPM_BUILD_ROOT%_sysconfdir/sysconfig/console/setterm
mkdir $RPM_BUILD_ROOT%_sysconfdir/sysconfig/harddisk

# Autogenerated kernel headers.
%__mkdir_p $RPM_BUILD_ROOT{/var/run/kernel,%_localstatedir/rsbac}
for f in {autoconf,modversions,version}.{h,ph} _h2ph_pre.ph; do
	touch "$RPM_BUILD_ROOT/var/run/kernel/$f"
done

%pre
[ $1 -eq 1 ] || /usr/sbin/control-dump usernetctl

%post
if [ $1 -eq 1 ]; then
	/sbin/chkconfig --add random
	/sbin/chkconfig --add netfs
	/sbin/chkconfig --add network
	/sbin/chkconfig --add rawdevices
	/sbin/chkconfig --add sound
	/sbin/chkconfig --add usb
	/sbin/chkconfig --add dm
else
	/usr/sbin/control-restore usernetctl
	if %__grep -qs '^x:5:' /etc/inittab; then
		/sbin/chkconfig --add dm
		%__subst 's/^x:5:/#x:5:/' /etc/inittab
	fi
fi

for f in /var/{log/wtmp,run/utmp}; do
	if [ ! -f "$f" ]; then
		:>>"$f"
		%__chown root.utmp "$f"
		%__chmod 664 "$f"
	fi
done

# Dup of timeconfig %%post - here to avoid a dependency.
if [ -L %_sysconfdir/localtime ]; then
	_FNAME=`/bin/ls -ld %_sysconfdir/localtime |/bin/awk '{print $11}' |/bin/sed 's/lib/share/'`
	if [ -f "$_FNAME" ]; then
		%__rm %_sysconfdir/localtime
		%__cp -fp "$_FNAME" %_sysconfdir/localtime
		if ! %__grep -q "^ZONE=" %_sysconfdir/sysconfig/clock; then
			echo "ZONE=\"$_FNAME"\" |/bin/sed -e "s|[^\"]*/usr/share/zoneinfo/||" >>%_sysconfdir/sysconfig/clock
		fi
	fi
fi

%preun
if [ $1 -eq 0 ]; then
	/sbin/chkconfig --del random
	/sbin/chkconfig --del netfs
	/sbin/chkconfig --del network
	/sbin/chkconfig --del rawdevices
	/sbin/chkconfig --del sound
	/sbin/chkconfig --del usb
	/sbin/chkconfig --del dm
fi

%triggerpostun -- initscripts < 5.49
/sbin/chkconfig --add random
/sbin/chkconfig --add netfs
/sbin/chkconfig --add network
/sbin/chkconfig --add rawdevices
/sbin/chkconfig --add sound
/sbin/chkconfig --add usb
/sbin/chkconfig --add dm

%triggerpostun -- initscripts <= 5.49-ipl50mdk
/sbin/chkconfig --add dm

%triggerpostun -- %name <= 4.72
. %_sysconfdir/sysconfig/init
. %_sysconfdir/sysconfig/network

# These are the non-default settings. By putting them at the end
# of the %_sysconfdir/sysctl.conf file, it will override the default
# settings earlier in the file.

if [ -n "$FORWARD_IPV4" ] && [ "$FORWARD_IPV4" != "no" -a "$FORWARD_IPV4" != "false" ]; then
	echo "# added by initscripts install on `date`" >>%_sysconfdir/sysctl.conf
	echo "net.ipv4.ip_forward = 1" >>%_sysconfdir/sysctl.conf
fi
if [ -n "$DEFRAG_IPV4" ] && [ "$DEFRAG_IPV4" != "no" -a "$DEFRAG_IPV4" != "false" ]; then
	echo "# added by initscripts install on `date`" >>%_sysconfdir/sysctl.conf
	echo "net.ipv4.ip_always_defrag = 1" >>%_sysconfdir/sysctl.conf
fi
if [ -n "$MAGIC_SYSRQ" ] && [ "$MAGIC_SYSRQ" != "no" -a "$MAGIC_SYSRQ" != "false" ]; then
	echo "# added by initscripts install on `date`" >>%_sysconfdir/sysctl.conf
	echo "kernel.sysrq = 1" >>%_sysconfdir/sysctl.conf
fi
if uname -m |fgrep -q sparc; then
	if [ -n "$STOP_A" -a "$STOP_A" != "no" -a "$STOP_A" != "false" ]; then
		echo "# added by initscripts install on `date`" >>%_sysconfdir/sysctl.conf
		echo "kernel. = 1" >>%_sysconfdir/sysctl.conf
	fi
fi

%files
%config %verify(not md5 mtime size) %attr(640,root,root) %_sysconfdir/adjtime
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/clock
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/framebuffer
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/i18n
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/init
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/keyboard
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/mouse
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/network
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/rawdevices
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/system
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/usb
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/vlan
%config /sbin/ifdown
%config /sbin/ifup
%dir %_sysconfdir/sysconfig/harddisk
%dir %_sysconfdir/sysconfig/console
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/console/setterm
%dir %_sysconfdir/sysconfig/network-scripts
%_sysconfdir/sysconfig/network-scripts/ifup
%_sysconfdir/sysconfig/network-scripts/ifdown
%config %_sysconfdir/sysconfig/network-scripts/*-*
%config %_sysconfdir/X11/prefdm
%config(noreplace) %_sysconfdir/inittab
%_sysconfdir/init.d
%dir    %_sysconfdir/rc.d
%dir    %_sysconfdir/rc.d/rc?.d
%config(missingok) %_sysconfdir/rc.d/rc?.d/*
%dir    %_sysconfdir/rc.d/scripts
%config %_sysconfdir/rc.d/scripts/*
%dir    %_sysconfdir/rc.d/init.d
%config %_sysconfdir/rc.d/init.d/*
%config %_sysconfdir/rc.d/rc
%config %_sysconfdir/rc.d/rc.sysinit
%config %_sysconfdir/rc.d/rc.powerfail
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/modules
%config(noreplace) %_sysconfdir/sysctl.conf
%config %_sysconfdir/profile.d/*
%config /etc/control.d/facilities/usernetctl
%_sbindir/sys-unconfig
%_sbindir/rundm
/sbin/setsysfont
%attr(4711,root,root) %_sbindir/usernetctl
/sbin/consoletype
/sbin/getkey
%attr(2711,root,netwatch) /sbin/netreport
/sbin/initlog
/sbin/minilogd
/sbin/service
/sbin/ppp-watch
%config %_sysconfdir/ppp/ip-up
%config %_sysconfdir/ppp/ip-down
%config %_sysconfdir/initlog.conf
%dir %attr(770,root,netwatch) /var/run/netreport
%ghost %attr(664,root,utmp) /var/log/wtmp
%ghost %attr(664,root,utmp) /var/run/utmp
%ifnarch sparc
%_sbindir/supermount
%endif
/bin/*
%_bindir/*
%_mandir/man?/*
%dir /var/run/kernel
%ghost /var/run/kernel/*
%dir %_localstatedir/rsbac
%doc sysconfig.txt sysvinitfiles ChangeLog*

%changelog
* Sat Apr 19 2003 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl54mdk
- %_initdir/sound: don't sort aliases in LoadModule (#0001802).
- %_initdir/clock: test $HWCLOCK_ADJUST also for "true" value (#0002351).
- %_initdir/functions:
  + fixed check logic in daemon() a bit (#0002407).
  + fixed return code in killproc() (#0002412).
- %_initdir/outformat: check argumnets being passed to tput (#0002450).
- /etc/sysctl.conf:
  + set "net.ipv4.icmp_echo_ignore_broadcasts = 1" by default (#0002472);
  + added comments from Owl's sysctl.conf file.
- usernetctl: support variable definitions quoted with single quotes.

* Sun Mar 16 2003 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl53mdk
- Scripts cleanup:
  Most of bash-specific constructions were replaced with more
  standard ones; all the rest were marked as bash scripts.
- No new features were added but few old ones were removed.

* Wed Mar 05 2003 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl52mdk
- Removed /proc/progress support.
- %_initdir/dm: keep current fgconsole.

* Mon Mar 03 2003 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl51mdk
- Implemented rundm:
  %_sbindir/rundm: new program;
  %_initdir/dm: new startup script;
  %_sysconfdir/inittab: removed prefdm entry;
  %%post,%%preun,%%triggerpostun: added dm service support.

* Mon Feb 10 2003 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl50mdk
- /sbin/setsyfont: new version from imz (#0001048, #0002083).

* Mon Feb 03 2003 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl49mdk
- network-scripts/ifup-post:
  + fixed PEERDNS/RESOLV_MODS support (at);
  + fixed POSTFIX_CONFIG update support.

* Sat Dec 28 2002 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl48mdk
- init.d/outformat: fixed MOVE_TO_COL (#0001767).
- scripts/adjust_autofs: relocated to autofs package.
- rc.d/rc: ignore buggy subsystems.

* Sun Dec 15 2002 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl47mdk
- rc.sysinit, init.d/outformat: back to use $COLUMNS (#0001117).
- scripts/cleanup:
  + keep more quota files;
  + create lastlog if missing.
- scripts/adjust_autofs: add skipstart support (required for fix #0000530).

* Sun Dec 08 2002 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl46mdk
- network-scripts/ifup: fixed vlan_id calculation.
- init.d/network: fixed filtering vlan interfaces.
- init.d/outformat: new output formatting code (#0001117).
- scripts/gen_kernel_headers: regenerate headers only if necessary (#0001537).
- init.d/functions: fixed --bg option again (#0001600).
- ppp/ip-up: moved "sendmail -q" code to sendmail-common package (#0001605).
- init.d/clock: fixed "hwclock" issue (#0001611).
- rc.sysinit: fixed fsck error code handling (#0001675).

* Mon Oct 14 2002 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl45mdk
- network-scripts/ifup: added PEERNTP logic to dhcpcd; (#0001263).
- init.d/single: fixed; (#0001324).
- profile.d/inputrc.{sh,csh}: removed; (#0001327).
- profile.d/lang.{sh,csh): removed 'C->en_US' convertion; (#0001403).
- ppp/ip-up: added /etc/ppp/ip-up.d/ support.
- ppp/ip-down: added /etc/ppp/ip-down.d/ support.
- Added control support for usernetctl.

* Tue Jun 18 2002 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl44mdk
- init.d/sound: changed chkconfig values.
- TODO:
  + move all X11 stuff to xinitrc;
  + move all network stuff to separate subpackage;
  + consider moving sound and usb stuff to separate subpackage.

* Thu Jun 06 2002 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl43mdk
- profile.d/inputrc.{sh,csh}: moved LESS* rules to separate files
  (now in less package).

* Tue Jun 04 2002 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl42mdk
- init.d/usb: added support for multiple usb interfaces.

* Sun Jun 02 2002 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl41mdk
- Moved utilities to sh-utils package:
  /bin/getuseruid, /bin/runas, /bin/usleep - from initscripts.
- Moved requires to interactivesystem package:
  bdflush, mingetty.
- Fixed %%post: call "/sbin/chkconfig --add" only for first package install.
- Fixed typo in /etc/profile.d/inputrc.csh script.
- Removed %%config attributre from symlinks in %_sysconfdir/sysconfig/network-scripts/

* Mon Apr 15 2002 Dmitry V. Levin <ldv@alt-linux.org> 5.49-ipl40mdk
- Added sample rc.powerfail script.
- inittab:
  + cleaned up;
  + added comments and examples from Owl;
  + changed single-user mode action to /sbin/sulogin
    (closes #0000753, #0000683).
- scripts/first_time: added update-menus call.

* Mon Apr 15 2002 Dmitry V. Levin <ldv@alt-linux.org> 5.49-ipl39mdk
- Moved all useful from mandrake_everytime to rc.sysinit,
  and dropped mandrake_everytime.
- Renamed mandrake_firstime to first_time, dropped obsolete code.
- Relocated rc.local to init.d/local (so rc.local is user-defined now).
- Fixed:
  + init.d/clock: message typo (#0000451);
  + /sbin/if{up,down}-post: fixed typo, changed hooks for if{up,down}-local (#0000514);
  + init.d/functions: check for multi-word arguments for pidofproc/pidfileofproc (#0000515);
  + scripts/adjust_autofs: don't start autofs (#0000530);
  + init.d/local: fbprogress support: switching to tty1 only
    for "N --> [234]" runlevel change (#0000685).
  + manpage typos (#0000819);

* Fri Jan 18 2002 Dmitry V. Levin <ldv@alt-linux.org> 5.49-ipl38mdk
- network-scripts/ifup: call dhcpxd with -w option (#0000401).
- scripts/adjust_autofs: try to start automounter after config creation.
- scripts/indexhtml_update: test directory presence before chdir.

* Tue Jan 15 2002 Dmitry V. Levin <ldv@alt-linux.org> 5.49-ipl37mdk
- Added vlan support (dvlsakh, #0000363).

* Wed Jan 09 2002 Dmitry V. Levin <ldv@alt-linux.org> 5.49-ipl36mdk
- scripts/mandrake_everytime: call update_wms instead of fndSession.
- profile.d/lang.sh: test for non-empty i18n config, presence isn't enough.
- profile.d/tmpdir.sh: fixed $SECURE_TMP handling.
- init.d/usb: always probe usb-interface (goldhead).
- scripts/adjust_autofs: fixed TABFILE support.
- scripts/framebuffer_setfont: call setsysfont if and only if required.
- sysconfig/framebuffer: enable by default.

* Fri Jan 04 2002 Dmitry V. Levin <ldv@alt-linux.org> 5.49-ipl35mdk
- scripts/adjust_autofs: added TABFILE support.
- network-scripts/ifup: removed unneeded quotes for $RFLAG (#0000315).
- rc,rc.local: removed unnecessary chvt dependence.

* Wed Dec 26 2001 Dmitry V. Levin <ldv@alt-linux.org> 5.49-ipl34mdk
- Added LPP support (goldhead).

* Tue Dec 18 2001 Dmitry V. Levin <ldv@alt-linux.org> 5.49-ipl33mdk
- Fixed typo in lang.sh (svd).
- Fixed versioned dependencies.

* Fri Dec 14 2001 Dmitry V. Levin <ldv@alt-linux.org> 5.49-ipl32mdk
- Addeded inittab-generated requires: bdflush, mingetty (#0000180).
- rc.sysinit: added "modprobe lvm-mod" before testing /proc/lvm (#0000115).
- lang.sh: dropped RPM_INSTALL_LANG support.
- rc.local: added welcome2l support.
- usb: enable by default.
- rc.sysinit: set kernel.hotplug.
- init.d/network: disable kernel.hotplug during interfaces startup.

* Wed Nov 14 2001 Dmitry V. Levin <ldv@alt-linux.org> 5.49-ipl31mdk
- Moved bootloader stuff to separate package.

* Wed Sep 12 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl30mdk
- mandrake_firstime:
  + create /dev/dvd* symlinks if required;
  + create missing user mailboxes;
  + execute distribution-specific script: /etc/rc.d/scripts/distribution.

* Mon Aug 20 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl29mdk
- init.d/halt: reworked apcupsd and poweroff handling.

* Wed Aug 15 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl28mdk
- init.d/halt: in case of poweroff, call "modprobe apm";
- scripts/framebuffer_init: fixed typo;
- scripts/framebuffer_setfont: added "sleep 1" (temporary hack);
- scripts/idetune: added more harddisks; corrected hdparm parameter checks.

* Tue Jul 31 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl27mdk
- Added framebuffer device initialization support (goldhead).
- lang.sh: added iso08* to the list of '\033(K'-wanting SYSFONTACMs (aen).
- prefdm: redirect output from kdm to /dev/null (goldhead).
- functions: fixed type in --bg option parsing.
- rc.sysinit: relocated modprobing calls to reduce spam.

* Tue Jul 17 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl26mdk
- Added autofs support (at firsttime stage).
- network-functions: optimized a bit (mookid).

* Mon Jun 18 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl25mdk
- mandrake_firstime: remove also plain files from /.??*

* Tue Jun 05 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl24mdk
- Fixed bugs due to recent changes.

* Tue Jun 05 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl23mdk
- Everytime at startup touch if missing files: /etc/ld.so.{cache,preload} (for RSBAC).
- supermount script: put "$dev" in the first (device) field of a supermount entry (imz).
- prefdm: added WindowMaker support (voins).
- functions: set locale to POSIX for root.
- functions: sort remaining filesystems in UnmountFilesystems() (Alex Morozov).
- halt: update UnmountFilesystems patterns (idea from Alex Morozov).
- gen_kernel_headers: added support for various USR_LIB_KERNEL (idea from Alex Morozov).
- Moved some obsoletes to requires.

* Fri May 11 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl22mdk
- Set "aumix -v90 -w90" by default for alsa sound.

* Thu May 10 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl21mdk
- s|sysctl -p /etc/sysctl.conf|sysctl -e -p /etc/sysctl.conf|g

* Wed Apr 25 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl20mdk
- Reformat banner.
- Fixed init.d/netfs script.
- Re-added NIS domain initialization (dropped since 5.49-ipl7mdk).

* Mon Apr 23 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl19mdk
- Fixed rsbac softmode check.
- Updated %%distribution information.

* Fri Apr 20 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl18mdk
- network-scripts/ifup-post: fixed PEERDNS check; added SMTP_RELAYHOST support.
- init.d/usb: fixed usb mounting; changed startup level to 04.

* Thu Apr 19 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl17mdk
- Moved main rsbac stuff to separate package (secfiles).
- Fixed usb unmounting.
- Added rebuilding mozilla registry on first boot.

* Mon Apr 16 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl16mdk
- Added initial rsbac support.

* Mon Apr 16 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl15mdk
- Enhanced idetune script (cdrom support).

* Wed Apr 04 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl14mdk
- Various minor fixes.

* Tue Mar 20 2001 Dmitry V. Levin <ldv@altlinux.ru> 5.49-ipl13mdk
- Various fixes.

* Wed Mar 07 2001 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl12mdk
- Fixed typo in %_initdir/network.

* Mon Mar 05 2001 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl11mdk
- Major RH/MDK merge.

* Sun Feb 04 2001 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl10mdk
- Rewritten kernel headers autogeneration.

* Thu Feb 01 2001 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl9mdk
- Fixed status() function (%_initdir/functions).
- Fixed console initialization (%_sysconfdir/profile.d/lang.*).

* Wed Jan 31 2001 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl8mdk
- Fixed %_initdir/clock.
- Added wireless support.

* Mon Jan 22 2001 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl7mdk
- Moved helper scripts from %_sysconfdir/rc.d/init.d/ to %_sysconfdir/rc.d/scripts/
- New helper: idetune.
- We don't set the NIS domain name anymore.
- RH fixes from %name-5.54.

* Sun Jan 21 2001 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl6mdk
- Improved SourceIf* functions.
- Fixed interactive startup selection.
- Added %_sysconfdir/sysconfig/keyboard.
- Removed %_sysconfdir/sysconfig/pcmcia
  (it's now provided by pcmcia-cs package).
- Minor code cleanup.

* Sat Jan 06 2001 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl5mdk
- Fixes in installkernel (from Ivan Zakharyaschev <vanyaz@mccme.ru>).
- Added /usr/share/postfix/rebuild_aliases in mandrake_firstime.

* Wed Dec 27 2000 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl4mdk
- Fixed "pidofproc" in /etc/init.d/functions.

* Thu Dec 21 2000 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl3mdk
- Updated %_sysconfdir/profile.d/inputrc.sh.
- Added "PreReq: setup >= 2.1.9-ipl15mdk".

* Wed Dec 13 2000 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl2mdk
- Added more helper functions (/etc/init.d/functions).
- Updated bootup code and help files.

* Tue Dec 05 2000 Dmitry V. Levin <ldv@fandra.org> 5.49-ipl1mdk
- 5.49 - BigMerge with RH.

* Sat Dec 02 2000 Dmitry V. Levin <ldv@fandra.org> 5.27-ipl38mdk
- 5.27 - BigMerge with MDK (all except aurora).

* Wed May 31 2000 Dmitry V. Levin <ldv@fandra.org> 4.97-ipl42mdk
- RE and Fandra adaptions.

* Tue May 30 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-42mdk
- mandrake/installkernel: fix typo.

* Mon May 29 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-41mdk
- mandrake/usb: Don't load/unload keyboard on alpha (usb keyboard
  are builtins in alpha).
- mandrake/tmpdir.csh: Remove the /bin/csh to don't depend of csh.
- rc.d/rc.sysinit: Better devfs support (titi).
- mandrake/inputrc.csh: Remove = (not needed).

* Sun May 28 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-40mdk
- mandrake/Makefile: Include usb for alpha.
- initscripts.spec: Include usb for alpha.

* Sun May 28 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-39mdk
- mandrake/mandrake_everytime: Always clean /tmp/esrv* and
  /tmp/kio* files when CLEAN_TMP is set.
- mandrake/mandrake_everytime: Don't disable supermount	 on sparc
  (not even present).
- mandrake/usb: if USB=no in /etc/sysconfig/usb return 0
- mandrake/rc.modules: Fix typo.
- mandrake/installkernel: remove the \. from the label for lilo to
  minimize the chars.
- mandrake/installkernel: don't try to do something with lilo or
  grub when we are not on a x86 machines.
- mandrake/installkernel: Add --quiet options.
- mandrake/installkernel: remove the mdk for secure for lilo to minimize
  the chars.
- mandrake/Makefile: Add binfmt_aout to /etc/modules on alpha for netscape.
- rc.d/rc.sysinit: Merge Adam Lesback <adam@mandrakesoft.com> ppc change.

* Fri May 26 2000 Adam Lebsack <adam@mandrakesoft.com> 4.97-38mdk
- Patch for rc.sysinit for Powermac clock

* Tue May 23 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-37mdk
- mandrake/Makefile: Add various if{,n}eq $(ARCH) for alpha and sparc.
- mandrake/initscripts.spec: Add various %ifarch for alpha and sparc.

* Tue May 16 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-36mdk
- mandrake/kheader: exit 0 when no mdk kernel.

* Wed May 10 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-35mdk
-  mandrake/inputrc.csh: Fix typo (jerome).

* Mon May  8 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-34mdk
- mandrake/usb: set sleep between loading interfaces.

* Sun May  7 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-33mdk
- mandrake/mandrake_firstime: fix when setting mixer and there is
 no mixer.

* Sat May  6 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-32mdk
- sysconfig/network-scripts/(ifup|ifdown): Set by default dhcpcd not dhcpxd.
- rc.d/init.d/network: Set ipv4 forwarding when  FORWARD_IPV4=(yes|true).

* Fri May  5 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-31mdk
- mandrake/usb: Add printer support.

* Fri May  5 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-30mdk
- mandrake/mandrake_firstime: set the mixer to 80% by default.
- mandrake/sound: use of aumix even for alsa.  printk=0 when loading
  modules.

* Tue May  2 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-29mdk
- rc.d/init.d/netfs: starting and stopping netfs properly.
- sysconfig/network-scripts/ifup{-aliases,plip}: remove old kernel
  compatibilities.

* Fri Apr 28 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-28mdk
- sysconfig/network-scripts/ifup (DHCP_ARGS): fix ugly ''basename
  command not found''
- sysconfig/network-scripts/ifdown (CONFIG): fix support for
  multiple dhcp client.

* Wed Apr 26 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-27mdk
- mandrake/usb: fix mounting proc usb and umount usbdevfs when stoping.
- mandrake/kheader: exit 0 when no mdk kernel.

* Mon Apr 24 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-26mdk
- mandrake/installkernel (grub_device): root=$root_device not $kversion.

* Mon Apr 24 2000 Pixel <pixel@mandrakesoft.com> 4.97-25mdk
- mandrake/usb: fix missing 'fi'

* Sun Apr 23 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-24mdk
- mandrake/sound: Add alsa support.

* Sun Apr 23 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-23mdk
- mandrake/installkernel: move from kernel to here.
- mandrake/usb: Mount usbdevfs if present.
- mandrake/detectloader: Don't detect cdrom.

* Wed Apr 19 2000 Pixel <pixel@mandrakesoft.com> 4.97-22mdk
- mandrake/mandrake_firstime: call postinstall.sh for webmin if there

* Tue Apr 18 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-21mdk
- mandrake/detectloader.8: man pages of detectloader.
- mandrake/detectloader: A new greatest hit.

* Mon Apr 17 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-20mdk
- rc.d/rc: if no askrunlevel installed jump directly to runlevel 1.
- rc.d/rc: s|ASKRUNLEVEL|failsafe|;
- rc.d/rc.sysinit: s|ASKRUNLEVEL|failsafe|;

* Sun Apr 16 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-19mdk
- rc.d/rc.sysinit: check if ASKRUNLEVEL arg.
- rc.d/rc: if specify ASKRUNLEVEL on commandline then run
askrunlevel interactively.
- rc.d/rc: if we found the tag "halt: yes" then stop the script even
if no subsytem is touched.
- sysconfig/network-scripts/network-functions: /dev/null some
error message.
- sysconfig/network-scripts/ifdown: Check to make sure the device
is actually up
- src/netreport.c (main): if no args then show usage.
- src/minilogd.c: stat the PATH_LOG better.
- service: add --full-restart options.
- rc.d/rc.sysinit (CLOCKFLAGS): if no UTC then set up as localtime.
- rc.d/init.d/network: If this is a final shutdown/halt, check for
network FS, and unmount them even if the user didn't turn on netfs
- rc.d/init.d/network: setting syscontrol network here.
- rc.d/init.d/network: fix typos.
- rc.d/init.d/halt: specify when retrying to umount devices.
- ppp/ip-up: using "$@" instead of "$*"
- ppp/ip-down: using "$@" instead of "$*"
- mandrake/sound: Add level 6 in chkconfig.

* Thu Apr 13 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-18mdk
- initscripts.spec: Conflicts: linuxconf <= 1.17r9 (for askrunlevel).
- mandrake/sound: new script.
- rc.d/rc.sysinit: check for executable when launching rc.modules.
- rc.d/rc.sysinit: remove sound stuff.
- rc.d/init.d/halt: remove sound stuff.
- rc.d/rc: if user ask for interactive setup, launch askrunlevel
  to change runlevel on the fly and (re)configure system before
  booting.

* Wed Apr 12 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-17mdk
- mandrake/usb: Try to find a usb adaptator.
- mandrake/usb: zip support.
- mandrake/supermount: lots of supermount fix from <denis@mandrakesoft.com>.

* Thu Apr  6 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-16mdk
- sysconfig.txt: Upgrade doc.
- mandrake/mandrake_everytime: Clean up /tmp if it choose at
  install.
- rc.d/init.d/halt: don't umount /var/shm do this from
  /etc/fstab.
- rc.d/rc.sysinit: don't mount /var/shm do this from
  /etc/fstab.

* Wed Apr  5 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-15mdk
- mandrake/supermount: add a chmod 0644 after writing the file
  (don't be nazi, let's permit the simple user to read the
  /etc/fstab file :\).

* Wed Apr  5 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-14mdk
- mandrake/supermount: fix multiple bugs (multiple cdrom, handle options).
- mandrake/mandrake_everytime: don't use insmod -p to detect is supermount
  module is here.

* Mon Apr  3 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-13mdk
- rc.d/init.d/network: don't exclude ipp[0-9] from interfaces.

* Fri Mar 31 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-12mdk
- rc.d/rc.sysinit:  devfsd, shm support (titi).
- rc.d/init.d/halt: shm support (titi).

* Tue Mar 28 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-11mdk
- initscripts.spec: Add sysctl.conf in %files.

* Sat Mar 25 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-10mdk
- rc.d/rc.sysinit: ignore failure of symlinking System.map (aka	stderr to dave null)(pixel).
- mandrake/modules: new file kernel modules to load at boot time (btw: add vfat).
- mandrake/rc.modules: new file to load modules of /etc/modules.
- mandrake/supermount: Fix typo and chmou stupidity.
- mandrake/Makefile: Add kheader/rc.modules/modules.
- mandrake/mandrake_everytime: use better approach to detect if
  supermount modules is not present.
- mandrake/mandrake_everytime: Remove the modprobe vfat.
- mandrake/mandrake_firstime: erase first logfile if the file is empty.
- initscripts.spec: Add kheader in %post %preun.
- initscripts.spec: Add rc.modules and modules in %files.
- initscripts.spec: chkconfig --del usb in %preun.
- initscripts.spec: Add changeLog in %doc.
- rc.d/rc.sysinit: remove generation of /boot/kernel.h (moved to
	kheader script).
- mandrake/kheader: new file
- mandrake/usb: fix description.
- sysconfig.txt: upgrade documentation.
- sysconfig/network-scripts/ifup: if BOOTPROTO=bootp launch them
  via pump.
- sysconfig/network-scripts/ifup: by default launch dhcpxd for
  DHCP if is not installed launch dhclient || dhcpcd || pump. If
  the variable DHCP_CLIENT= is specified in ifcfg-$device configure
  this one.

* Wed Mar 22 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-9mdk
- rc.d/rc.sysinit: fix buggy call in linuxconf stuff.
- mandrake/Makefile: include is_depmod_necessary
- mandrake/is_depmod_necessary.c: move it here from modutils package.

* Tue Mar 21 2000 Pixel <pixel@mandrakesoft.com> 4.97-8mdk
- rc.d/init.d/halt: added removing of entry /initrd/loopfs in
/etc/mtab. removed unused lnx4win stuff

- rc.d/rc.sysinit: added adding of entry /initrd/loopfs in
/etc/mtab

- rc.d/rc.sysinit: move the chmou linuxconf stuff (buggy by the
way, sed doesn't exit code depending on succeeding subst)

* Sun Mar 19 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-7mdk
- mandrake/Makefile: fix typo.
- initscripts.spec: Conflicts with linuxconf <= 1.17r5
- rc.d/rc.sysinit: preliminary linuxconf profile support.
- rc.d/rc.local: don't display too much information in issue.net
  if SECURITY_LEVEL => 4.
- mandrake/supermount.8: minor modifications.
- mandrake/usb: remove unused sleep
- initscripts.spec: add inputrc.csh in %files.

* Sat Mar 18 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-6mdk
- initscripts.spec: add inputrc.csh in %files.

* Thu Mar 16 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-5mdk
- initscripts.spec: requires setup >= 2.1.9-3mdk (for inputrc).

* Mon Mar 13 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-4mdk
- initscripts.spec: Adjust groups.

* Mon Mar 13 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-3mdk
- rc.d/rc.sysinit: Remove nasty mount /boot stuff (pixel)
- mandrake/usb: Get working with the new configuration scheme for usb.
- mandrake/usb: Preferring to use usb-interface to usb-mouse-interface.

* Sun Mar 12 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.97-2mdk
- *: upgrade to 4.97.
- ChangeLog: new one.
- initscripts.spec: clean-up spec.
- sysconfig/network-scripts/ifup: fix typo.
- sysctl.conf: sysrq = 1 on mandrake.
- service: Exclude mandrake_firstime | mandrake_everytime.
- mandrake/usb: make compatible with usb backport.

* Sun Feb  6 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.72-14mdk
- Don't optimize for DVD-ROM(#740).

* Wed Jan 12 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.72-13mdk
- Fix wrong supermount man pages.

* Fri Jan  7 2000 Pixel <pixel@mandrakesoft.com> 4.72-12mdk
- more intelligent prefdm (in case of bad sysconfig/desktop)

* Thu Jan  6 2000 Chmouel Boudjnah <chmouel@mandrakesoft.com> 4.72-11mdk
- remove the -i switch to dhcpd (thanks Gary Simmons <darshu@sympatico.ca).

* Thu Dec 30 1999 Chmouel Boudjnah <chmouel@mandrakesoft.com>
- Add supermount manpages (camille).

* Wed Dec 29 1999 Chmouel Boudjnah <chmouel@mandrakesoft.com>
- Add a supermount script to disable or enable supermount.
- fix typos.

* Wed Dec 29 1999 Chmouel Boudjnah <chmouel@mandrakesoft.com>
- Add makewhatis on first boot.

* Fri Dec 24 1999 Frederic Lepied <flepied@mandrakesoft.com> 4.72-4mdk
- fix halt not to call umount /proc.

* Tue Dec 21 1999 Chmouel Boudjnah <chmouel@mandrakesoft.com>
- 4.72.
- Fix a lot of bugs.
