#!/bin/sh

PATH=/bin:/usr/bin

[ -s /etc/sysconfig/i18n ] && . /etc/sysconfig/i18n

CONSOLECHARS=
for f in /bin/consolechars /usr/bin/consolechars; do
	if [ -x "$f" ]; then
		CONSOLECHARS="$f"
		break
	fi
done

SETFONT=
for f in /bin/setfont /usr/bin/setfont; do
	if [ -x "$f" ]; then
		SETFONT="$f"
		break
	fi
done

if [ -n "$CONSOLECHARS" ]; then
  if [ -n "$SYSFONT" ]; then
    if [ -f /etc/sysconfig/console/$SYSFONT.psf* ]; then
    	ARGS="/etc/sysconfig/console/$SYSFONT.psf.gz"
	else
    	ARGS="$SYSFONT"
	fi
    if [ -n "$UNIMAP" ]; then
    	if [ -f /etc/sysconfig/console/$UNIMAP.sfm* ]; then
    		ARGS="$ARGS --sfm /etc/sysconfig/console/$UNIMAP.sfm"
		else
			ARGS="$ARGS --sfm $UNIMAP"
		fi
    fi
    if [ -n "$SYSFONTACM" ]; then
    	if [ -f /etc/sysconfig/console/$SYSFONTACM.acm* ]; then
    		ARGS="$ARGS --acm /etc/sysconfig/console/$SYSFONTACM.acm"
		else
			ARGS="$ARGS --acm $SYSFONTACM"
		fi
    fi
    "$CONSOLECHARS" $@ -f $ARGS
  fi
elif [ -n "$SETFONT" ]; then
  if [ -n "$SYSFONT" -a -n "$UNIMAP" ]; then
    "$SETFONT" $SYSFONT -u $UNIMAP
  elif [ -n "$SYSFONT" ]; then
    "$SETFONT" $SYSFONT
#  else
#    /usr/bin/setfont
  fi
else
  echo "cannot set font" >&2
  exit 1
fi
exit 0
