#!/bin/sh

# Source library functions
. /etc/init.d/functions

CONSOLECHARS=
for f in /bin/consolechars /usr/bin/consolechars; do
	if [ -x "$f" ]; then
		CONSOLECHARS="$f"
		break
	fi
done

SETFONT=
for f in /bin/setfont /usr/bin/setfont; do
	if [ -x "$f" ]; then
		SETFONT="$f"
		break
	fi
done

if [ -n "$CONSOLECHARS" ]; then
	if [ -n "$SYSFONT" ]; then
		if a=`FindFile /etc/sysconfig/console/$SYSFONT.psf`; then
			ARGS="$a"
		else
			ARGS="$SYSFONT"
		fi
	fi
    if [ -n "$UNIMAP" ]; then
		if a=`FindFile /etc/sysconfig/console/$UNIMAP.sfm`; then
			ARGS="$ARGS --sfm $a"
		else
			ARGS="$ARGS --sfm $UNIMAP"
		fi
	fi
    if [ -n "$SYSFONTACM" ]; then
		if a=`FindFile /etc/sysconfig/console/$SYSFONTACM.acm`; then
			ARGS="$ARGS --acm $a"
		else
			ARGS="$ARGS --acm $SYSFONTACM"
		fi
    fi
    "$CONSOLECHARS" "$@" -f $ARGS
elif [ -n "$SETFONT" ]; then
	if [ -n "$SYSFONT" -a -n "$UNIMAP" ]; then
		"$SETFONT" "$SYSFONT" -u "$UNIMAP"
	elif [ -n "$SYSFONT" ]; then
		"$SETFONT" "$SYSFONT"
	fi
else
	echo "cannot set font" >&2
	exit 1
fi
:
