# $Id$

Name: startup
Version: 0.0.1
Release: alt1

Summary: The system startup scripts
License: GPL
Group: System/Base
Packager: Dmitry V. Levin <ldv@altlinux.org>

Source: %name-%version.tar.bz2

PreReq: setup >= 0:2.1.9-ipl18mdk, chkconfig, gawk, grep, sed, coreutils

%description
This package contains scripts used to boot your system,
change runlevels, and shut the system down cleanly.

%prep
%setup -q

%install
%__mkdir_p $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc{0,1,2,3,4,5,6}.d
%__install -p -m644 inittab adjtime sysctl.conf $RPM_BUILD_ROOT%_sysconfdir/
%__instapp -pD -m755 setsysfont $RPM_BUILD_ROOT/sbin/setsysfont
%__cp -a rc.d sysconfig $RPM_BUILD_ROOT%_sysconfdir/

# these services do not support chkconfig:
# killall, halt, single local - Can't store symlinks in a CVS archive
%__ln_s ../init.d/killall $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc0.d/S00killall
%__ln_s ../init.d/killall $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc6.d/S00killall

%__ln_s ../init.d/halt $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc0.d/S01halt
%__ln_s ../init.d/halt $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc6.d/S01reboot

%__ln_s ../init.d/single $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc1.d/S00single

for i in `seq 2 5`; do
	%__ln_s ../init.d/local $RPM_BUILD_ROOT%_sysconfdir/rc.d/rc$i.d/S99local
done

# This is a LSB compatibility symlink.  We hope that some day
# the actual files will be here instead of symlinks.
for i in `seq 0 6`; do
	%__ln_s rc.d/rc$i.d $RPM_BUILD_ROOT%_sysconfdir/rc$i.d
done

touch $RPM_BUILD_ROOT/var/{log/wtmp,run/utmp}
touch $RPM_BUILD_ROOT%_sysconfdir/sysconfig/{clock,i18n,keyboard,mouse,system}
chmod -R +x $RPM_BUILD_ROOT%_sysconfdir/rc.d
%__mkdir_p $RPM_BUILD_ROOT%_sysconfdir/sysconfig/{console,harddisk}
touch $RPM_BUILD_ROOT%_sysconfdir/sysconfig/console/setterm

# Autogenerated kernel headers.
%__mkdir_p $RPM_BUILD_ROOT{/var/run/kernel,%_localstatedir/rsbac}
for f in {autoconf,modversions,version}.{h,ph} _h2ph_pre.ph; do
	touch "$RPM_BUILD_ROOT/var/run/kernel/$f"
done

%post
if [ $1 -eq 1 ]; then
	/sbin/chkconfig --add random
	/sbin/chkconfig --add rawdevices
	/sbin/chkconfig --add sound
	/sbin/chkconfig --add usb
fi

for f in /var/{log/wtmp,run/utmp}; do
	if [ ! -f "$f" ]; then
		:>>"$f"
		%__chown root.utmp "$f"
		%__chmod 664 "$f"
	fi
done

# Dup of timeconfig %%post - here to avoid a dependency.
if [ -L %_sysconfdir/localtime ]; then
	_FNAME=`/bin/ls -ld %_sysconfdir/localtime |/bin/awk '{print $11}' |/bin/sed 's/lib/share/'`
	if [ -f "$_FNAME" ]; then
		%__rm %_sysconfdir/localtime
		%__cp -fp "$_FNAME" %_sysconfdir/localtime
		if ! %__grep -q "^ZONE=" %_sysconfdir/sysconfig/clock; then
			echo "ZONE=\"$_FNAME"\" |/bin/sed -e "s|[^\"]*/usr/share/zoneinfo/||" >>%_sysconfdir/sysconfig/clock
		fi
	fi
fi

%preun
if [ $1 -eq 0 ]; then
	/sbin/chkconfig --del random
	/sbin/chkconfig --del rawdevices
	/sbin/chkconfig --del sound
	/sbin/chkconfig --del usb
fi

%files
%config %verify(not md5 mtime size) %attr(640,root,root) %_sysconfdir/adjtime
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/clock
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/framebuffer
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/i18n
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/init
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/keyboard
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/mouse
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/rawdevices
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/system
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/usb
%dir %_sysconfdir/sysconfig/harddisk
%dir %_sysconfdir/sysconfig/console
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/sysconfig/console/setterm
%config(noreplace) %_sysconfdir/inittab
%_sysconfdir/init.d
%dir    %_sysconfdir/rc.d/rc?.d
%config(missingok) %_sysconfdir/rc.d/rc?.d/*
%dir    %_sysconfdir/rc.d/scripts
%config %_sysconfdir/rc.d/scripts/*
%config %_sysconfdir/rc.d/init.d/*
%config %_sysconfdir/rc.d/rc
%config %_sysconfdir/rc.d/rc.sysinit
%config %_sysconfdir/rc.d/rc.powerfail
%config(noreplace) %verify(not md5 mtime size) %_sysconfdir/modules
%config(noreplace) %_sysconfdir/sysctl.conf
/sbin/setsysfont
%ghost %attr(664,root,utmp) /var/log/wtmp
%ghost %attr(664,root,utmp) /var/run/utmp
/bin/*
%_bindir/*
%_mandir/man?/*
%dir /var/run/kernel
%ghost /var/run/kernel/*
%dir %_localstatedir/rsbac

%changelog
* Mon Apr 21 2003 Dmitry V. Levin <ldv@altlinux.org> 0.0.1-alt1
- Removed all service and networking code and packaged them separately.
- Renamed to startup.

* Sat Apr 19 2003 Dmitry V. Levin <ldv@altlinux.org> 5.49-ipl54mdk
- %_initdir/sound: don't sort aliases in LoadModule (#0001802).
- %_initdir/clock: test $HWCLOCK_ADJUST also for "true" value (#0002351).
- %_initdir/functions:
  + fixed check logic in daemon() a bit (#0002407).
  + fixed return code in killproc() (#0002412).
- %_initdir/outformat: check argumnets being passed to tput (#0002450).
- /etc/sysctl.conf:
  + set "net.ipv4.icmp_echo_ignore_broadcasts = 1" by default (#0002472);
  + added comments from Owl's sysctl.conf file.
- usernetctl: support variable definitions quoted with single quotes.
