#!/bin/sh
#
# /etc/rc.d/scripts/cleanup - run once at boot time from rc.sysinit
#

. /etc/init.d/functions

SourceIfNotEmpty /etc/sysconfig/system

# Clean up /
rm -f /fastboot /fsckoptions /forcefsck /halt /poweroff

# Do we need (w|u)tmpx files? We don't set them up, but the sysadmin might...
_NEED_XFILES=
[ -f /var/run/utmpx -o -f /var/log/wtmpx ] && _NEED_XFILES=1

# Clean up /var
# I'd use find, but /usr may not be mounted.
for f in /var/lock/* /var/run/*; do
	if [ -d "$f" ]; then
		case "${f##*/}" in
			news|sudo)
				;;
			*)
				rm -rf -- "$f"/*
		esac
	else
		if [ "$f" != "/var/lock/TMP_1ST" ]; then
			rm -f -- "$f"
		fi
	fi
done

rm -f /tmp/.X*-lock
rm -f /tmp/esrv*
rm -f /tmp/k{fm,io}_*
rm -f /tmp/.s.PGSQL.*
rm -f /tmp/.MediaCon*
rm -rf /tmp/.ICE-unix
rm -rf /tmp/.esd*
rm -rf /tmp/kde-*
rm -rf /tmp/ksocket-*
rm -rf /tmp/mcop-*
rm -rf /tmp/orbit-*
rm -rf /tmp/ssh-*

# Clean up /tmp.
if [ -n "$CLEAN_TMP" ] && [ "$CLEAN_TMP" -ge 1 ]; then
	(
		cd /tmp &&
	    find . -xdev \
	    ! -ctime -$CLEAN_TMP \
	    ! -name . \
	    ! \( -name lost+found -uid 0 \) \
	    ! \( -name quota.user -uid 0 \) \
	    ! \( -name quota.group -uid 0 \) \
	    -depth -print0 | xargs -r0 rm -rf
	)
fi

# Clean up utmp/wtmp
:>/var/run/utmp
touch /var/log/wtmp
chgrp utmp /var/run/utmp /var/log/wtmp
chmod 0664 /var/run/utmp /var/log/wtmp
if [ -n "$_NEED_XFILES" ]; then
	:>/var/run/utmpx
	touch /var/log/wtmpx
	chgrp utmp /var/run/utmpx /var/log/wtmpx
	chmod 0664 /var/run/utmpx /var/log/wtmpx
fi
