#!/bin/sh
#
# /etc/init.d/console - run at boot time from rc.sysinit

# Source library functions
. /etc/init.d/functions

if [ -z "$NOLOCALE" ]; then
	# Load system font
	if [ -x /sbin/setsysfont ]; then
		if FindFile /etc/sysconfig/console/$SYSFONT.psf &>/dev/null ||
			FindFile /usr/lib/kbd/consolefonts/$SYSFONT.psf &>/dev/null; then
			action "Setting default font:" /sbin/setsysfont
		fi
	fi

	# Load keymap
	KEYMAP=
	if [ -f /etc/sysconfig/console/default.kmap ]; then
		KEYMAP=/etc/sysconfig/console/default.kmap
		action "Loading default keymap:" \
			"sh -c \"loadkeys $KEYMAP </dev/tty0 >/dev/tty0 2>/dev/null\""
	else
		INIT_KEYTABLE=/etc/init.d/keytable
		if [ -x "$INIT_KEYTABLE" -a -d /usr/lib/kbd/keymaps ]; then
			"$INIT_KEYTABLE" start
		fi
	fi   
fi

# Initialize screensaver
if [ -x /usr/bin/setterm -a -d /usr/share/terminfo -a -s /etc/sysconfig/console/setterm ]; then
	action "Initializing console powersaver:" \
		"sh -c \"/usr/bin/setterm `cat /etc/sysconfig/console/setterm` >/dev/console\""
fi
