#!/bin/sh
#
# /etc/rc.d/scripts/framebuffer - run once at boot time from inittab.

WITHOUT_RC_COMPAT=1

# Source function library.
. /etc/init.d/functions

# Parse framebuffer config.
SourceIfNotEmpty /etc/sysconfig/framebuffer && ! is_no "$ENABLE" || exit 0

sleep 1

# fbset program
FBSET=/usr/sbin/fbset

# Setup videomode if defined
if [ -n "$MODE" -a -x "$FBSET" ]; then
	"$FBSET" -a "$MODE" >>/dev/tty12 2>&1
fi

# Update system font
if [ -n "$MODULE" ] || [ -n "$MODE" -a -x "$FBSET" ]; then
	for i in $TTYS; do
		/sbin/setsysfont --tty=/dev/tty$i >>/dev/tty12 2>&1
	done
fi
