#!/bin/sh
#
# /etc/rc.d/scripts/framebuffer - run once at boot time from inittab.

. /etc/init.d/functions

# Parse framebuffer config.
SourceIfNotEmpty /etc/sysconfig/framebuffer && [ "$ENABLE" != no ] || exit 0

# fbset program
FBSET=/usr/sbin/fbset

# Setup videomode if defined
if [ -n "$MODE" -a -x "$FBSET" ]; then
	"$FBSET" -a "$MODE" >/dev/tty12 2>&1
fi

# Update system font
for i in $TTYS; do
    /sbin/setsysfont --tty=/dev/tty$i >/dev/tty12 2>&1
done
