#!/bin/sh

RSBAC_INIT="${0%/*}/rsbac_init"
[ -x "$RSBAC_INIT" ] || exit 0

fgrep -wqs rsbac_softmode /proc/cmdline || exit 0
uname -r |fgrep -qs rsbac || exit 0
mkdir -p /var/lib/rsbac || exit 0

LOCKFILE=/var/lib/rsbac/init.lock
if [ -f "$LOCKFILE" ]; then
	exit 0
fi

WITHOUT_RC_COMPAT=1

# Source function library.
. /etc/init.d/functions

if action "Adjusting RSBAC configuration:" "$RSBAC_INIT"; then
	touch "$LOCKFILE"
fi
