#!/bin/sh

which()
{
    PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/lib/postfix /usr/bin/which "$1" 2>/dev/null
}

export which

LOADER=`detectloader`
#check lilo&grub for rsbac_ lines
if [ "$LOADER" = LILO ]; then
    if [ -f /etc/lilo.conf ]; then
	grep -qs rsbac_auth_enable_login /etc/lilo.conf || exit 0
    fi 
else
    if [ -f /boot/grub/menu.lst ];then
	grep -qs rsbac_auth_enable_login /boot/grub/menu.lst || exit 0
    fi
fi

#check kernel
uname -r |fgrep -qs rsbac || exit 0

auth_set_cap=`which auth_set_cap` || exit 0
attr_set_fd=`which attr_set_fd` || exit 0

#sshd
if program=`which sshd`; then
#    echo $program
    "$attr_set_fd" FILE auth_may_setuid 1 $program
fi

#su for Postgres
if uid=`getuseruid postgres` && program=`which su`; then
#    echo "$uid $program"
    "$auth_set_cap" FILE add $program $uid
fi

auth_set_cap_program_anybody()
{
    program=`which $1` || return
#    echo "$auth_set_cap FILE add $program $uid"
    "$auth_set_cap" FILE add $program 0 399
    "$auth_set_cap" FILE add $program 401 16384
}

#xinetd
auth_set_cap_program_anybody xinetd

#crond
auth_set_cap_program_anybody crond

#atd
auth_set_cap_program_anybody atd

#at: FIXME swap_uid
auth_set_cap_program_anybody at

auth_set_cap_program_user()
{
    program=`which $1` || return
    uid=`getuseruid $2` || return
#    echo "$auth_set_cap FILE add $program $uid"
    "$auth_set_cap" FILE add "$program" "$uid"
}

# xfs
auth_set_cap_program_user xfs xfs

#portmap
auth_set_cap_program_user portmap rpc

#named
auth_set_cap_program_user named named

#scanlogd
auth_set_cap_program_user scanlogd scanlogd

#apache
auth_set_cap_program_user httpd apache

#libra-ftpd
auth_set_cap_program_user libra-ftpd libra-ftpd

#junkbuster
auth_set_cap_program_user exec_junkbuster junkbuster

#mysql
auth_set_cap_program_user mysqld mysql

#rcync
auth_set_cap_program_user rsync rsyncd

#cupsd
auth_set_cap_program_user cupsd lp

#postfix
if uid=`getuseruid postfix`; then
    postsuper_program=`which postsuper`
    qmgr_program=`which qmgr`
    cleanup_program=`which cleanup`
    trivialrewrite_program=`which trivial-rewrite`
    bounce_program=`which bounce`
    local_program=`which local`
    smtp_program=`which smtp`
    smtpd_program=`which smtpd`

#    echo "$uid $postsuper_program"
#    echo "$uid $qmgr_program"
#    echo "$uid $cleanup_program"
#    echo "$uid $trivialrewrite_program"
#    echo "$uid $bounce_program"
#    echo  $local_program
#    echo "$uid $smtp_program"
#    echo "$uid $smtpd_program"

    "$auth_set_cap" FILE add $postsuper_program $uid
    "$auth_set_cap" FILE add $qmgr_program $uid
    "$auth_set_cap" FILE add $cleanup_program $uid
    "$auth_set_cap" FILE add $trivialrewrite_program $uid
    "$auth_set_cap" FILE add $bounce_program $uid
    "$auth_set_cap" FILE add $smtp_program $uid
    "$auth_set_cap" FILE add $smtpd_program $uid

    "$attr_set_fd" FILE auth_may_setuid 1 $local_program
fi


#remove rsbac_ lines from lilo&grub
if [ -f /etc/lilo.conf ]; then
    cat /etc/lilo.conf | sed 's/ *rsbac_auth_enable_login//;s/ *rsbac_softmode//' >/etc/lilo.conf~tmp
    mv /etc/lilo.conf~tmp /etc/lilo.conf
fi

if [ -f /boot/grub/menu.lst ]; then
    cat /boot/grub/menu.lst | sed 's/ *rsbac_auth_enable_login//;s/ *rsbac_softmode//' >/boot/grub/menu.lst~tmp
    mv /boot/grub/menu.lst~tmp /boot/grub/menu.lst
fi

#if our loader LILO then restart it
if [ "$LOADER" = LILO ]; then
    LILO=/sbin/lilo
    [ -x "$LILO" ] && "$LILO" &>/dev/null ||:
fi

##########################################
# Now add some additional restrictions   #
##########################################

name=`awk -F: '{if($3=="400") print $1}' /etc/passwd |head -1`
if [ -n "$name" ]; then
    su $name -c ${0%/*}/rsbac_init_addon
fi
