#!/bin/sh
#
# /etc/init.d/cleanup - run once at boot time from rc.sysinit
#

. /etc/init.d/functions

SourceIfNotEmpty /etc/sysconfig/system

echo -n "Cleaning up temporary files from previous boot: "

# Clean up /
rm -f /fastboot /fsckoptions /forcefsck /halt /poweroff

# Do we need (w|u)tmpx files? We don't set them up, but the sysadmin might...
_NEED_XFILES=
[ -f /var/run/utmpx -o -f /var/log/wtmpx ] && _NEED_XFILES=1

# Clean up /var
# I'd use find, but /usr may not be mounted.
for f in /var/lock/* /var/run/*; do
	if [ -d "$f" ]; then
		case "${f##*/}" in
			news|sudo)
				;;
			*)
				rm -rf -- "$f"/*
		esac
	else
		if [ "$f" != "/var/lock/TMP_1ST" ]; then
			rm -f -- "$f"
		fi
	fi
done

# Delete X locks
rm -f /tmp/.X*-lock

# Esrv...
rm -f /tmp/esrv*

# Delete KDE sockets
rm -f /tmp/k{fm,io}_*

# Delete Postgres sockets
rm -f /tmp/.s.PGSQL.*

# Clean up /tmp.
if [ -n "$CLEAN_TMP" ] && [ "$CLEAN_TMP" -ge 1 ]; then
    find /tmp/ -xdev \
    ! -ctime -$CLEAN_TMP \
    ! -name . \
    ! \( -name lost+found -uid 0 \) \
    ! \( -name quota.user -uid 0 \) \
    ! \( -name quota.group -uid 0 \) \
    -depth -exec rm -rf -- {} \; 
fi

# Clean up utmp/wtmp
:>/var/run/utmp
touch /var/log/wtmp
chgrp utmp /var/run/utmp /var/log/wtmp
chmod 0664 /var/run/utmp /var/log/wtmp
if [ -n "$_NEED_XFILES" ]; then
	:>/var/run/utmpx
	touch /var/log/wtmpx
	chgrp utmp /var/run/utmpx /var/log/wtmpx
	chmod 0664 /var/run/utmpx /var/log/wtmpx
fi

echo_success
echo
