#!/bin/sh
#
# /etc/init.d/clock - run once at boot time
#

# Source function library.
. /etc/init.d/functions

ARCH=$(/bin/uname -m)

# Set the system clock.
ARC=0
SRM=0
UTC=0

if [ -f /etc/sysconfig/clock ]; then
	. /etc/sysconfig/clock

	# convert old style clock config to new values
	if [ "${CLOCKMODE}" = "GMT" ]; then
		UTC=true
	elif [ "${CLOCKMODE}" = "ARC" ]; then
		ARC=true
	fi
fi

CLOCKDEF=""

if [ "$ARCH" = "ppc" ];then
	CLOCKFLAGS="-s"
else
	CLOCKFLAGS="--hctosys"
fi

case "$UTC" in
	yes|true)
		CLOCKFLAGS="$CLOCKFLAGS -u"
		CLOCKDEF="$CLOCKDEF (utc)"
		;;
	no|false)
		CLOCKFLAGS="$CLOCKFLAGS --localtime"
		CLOCKDEF="$CLOCKDEF (localtime)"
esac

case "$ARC" in
	yes|true)
		CLOCKFLAGS="$CLOCKFLAGS -A"
		CLOCKDEF="$CLOCKDEF (arc)"
		;;
esac

case "$SRM" in
	yes|true)
		CLOCKFLAGS="$CLOCKFLAGS -S"
		CLOCKDEF="$CLOCKDEF (srm)"
		;;
esac

/sbin/hwclock $CLOCKFLAGS

action "Setting clock $CLOCKDEF: `date`" date
