#!/bin/sh

# chkconfig: 5 45 05
# description: This startup script launches the graphical display manager

# Source function library.
. /etc/init.d/functions

DM=/usr/sbin/rundm
LOCKFILE=/var/lock/subsys/dm
RETVAL=0

start()
{
	echo -n "Starting display manager: "
	daemon $DM
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch "$LOCKFILE"
	return $RETVAL
}

stop()
{
	local FGCONSOLE=/usr/bin/fgconsole
	local CHVT=/usr/bin/chvt
	local fgconsole=
	if [ -x "$FGCONSOLE" ]; then
		fgconsole=`$FGCONSOLE`
	fi

	echo -n "Stopping display manager: "
	killproc $DM
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f "$LOCKFILE"

	if [ -n "$fgconsole" -a -x "$CHVT" ]; then
		$CHVT "$fgconsole"
	fi
	
	return $RETVAL
}

restart()
{
	stop
	start
}

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	condstop)
		if [ -e "$LOCKFILE" ]; then
			stop
		fi
		;;
	condrestart)
		if [ -e "$LOCKFILE" ]; then
			restart
		fi
		;;
	status)
		status $DM
		RETVAL=$?
		;;
	*)
		echo "Usage: ${0##*/} {start|stop|restart|condstop|condrestart|status}"
		RETVAL=1
esac

exit $RETVAL
